/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.local.app;

/**
 *
 * @author FP594HT
 */
public class amostraDados extends javax.swing.JFrame {

    /**
     * Creates new form amostraDados
     */
    public amostraDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMemoriaUsada = new javax.swing.JLabel();
        SaidaDadosMemoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SaidaDadosRAM = new javax.swing.JLabel();
        LabelCPU = new javax.swing.JLabel();
        SaidaDadosCPU = new javax.swing.JLabel();
        LabelTemperatura = new javax.swing.JLabel();
        SaidaDadosTemperatura = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelMemoriaUsada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelMemoriaUsada.setText("Memória de massa:");
        getContentPane().add(LabelMemoriaUsada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 30));
        getContentPane().add(SaidaDadosMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 157, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Memória RAM:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 157, 34));
        getContentPane().add(SaidaDadosRAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 160, 31));

        LabelCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelCPU.setText("CPU:");
        getContentPane().add(LabelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 129, 36));

        SaidaDadosCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(SaidaDadosCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, 129, 21));

        LabelTemperatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTemperatura.setText("Temperatura");
        getContentPane().add(LabelTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 129, 34));

        SaidaDadosTemperatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(SaidaDadosTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 570, 129, 38));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setText("Recolhimento de Dados");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 230, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amostraDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amostraDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amostraDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amostraDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amostraDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCPU;
    private javax.swing.JLabel LabelMemoriaUsada;
    private javax.swing.JLabel LabelTemperatura;
    private javax.swing.JLabel SaidaDadosCPU;
    private javax.swing.JLabel SaidaDadosMemoria;
    private javax.swing.JLabel SaidaDadosRAM;
    private javax.swing.JLabel SaidaDadosTemperatura;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
